site_name: HGT Reports

nav:
  - Home: index.md
  - Strategies: 
      - Strategy 9: Strategy9/strategy9.md
      - Strategy 10: Strategy10/strategy10.md
      - Strategy 11: Strategy11/strategy11.md
      - Strategy 11D: Strategy11D/strategy11d.md
      - Strategy 12: Strategy12/strategy12.md
      - Strategy 13: Strategy13/Strategy13.md
      - Strategy 14: Strategy14/Strategy14.md
      - Strategy 15: 15_XLV/15_XLV.md
      - Strategy 16: 16_XLV/15_XLV.md
  - Feature Reports:
     - Stochastic:  IndicatorReports/Stochastic/Stochastic.md
     - VIX and SPX Products: IndicatorReports/VIX_Related_Products/VIX_Related_Products.md

theme:
  name: material
  logo: images/stocks.png
  favicon: images/favicon.ico

copyright: © 2023 Hunt Gather Trade. All rights reserved.

extra:
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/huntgathertrade
    - icon: fontawesome/brands/github
      link: https://github.com/larrykann
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kanncommalarry/

